baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowWordCount = true
  ShowFullTextinRSS = true

[params.favicon]
  main = "/images/favicon.ico"
  appleTouchIcon = "/images/apple-touch-icon.png"
  safariPinnedTab = "/images/safari-pinned-tab.svg"
  msapplicationTileImage = "/images/mstile-150x150.png"
  msapplicationTileColor = "#ffffff"
